nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.1.1.cjs

npmScopes:
  "beeclover":
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.pkg.github.com"
    npmAuthToken: "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"
